name: build-aarch64

on: [push]

jobs:
  build:
    name: Build translateLocally for AArch64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up QEMU + AArch64 support
        uses: docker/setup-qemu-action@v3

      - name: Set up AArch64 Docker
        uses: docker/setup-buildx-action@v3

      - name: Run build in aarch64 container
        uses: addnab/docker-run-action@v3
        with:
          image: multiarch/ubuntu-core:20-aarch64
          options: --platform linux/arm64
          run: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y \
              build-essential cmake git protobuf-compiler \
              libprotobuf-dev libsentencepiece-dev \
              libpcre2-dev libicu-dev qt6-base-dev

            cd /github/workspace
            mkdir build && cd build
            cmake ..
            ../cmake/fix_ruy_build.sh /github/workspace /github/workspace/build
            make -j$(nproc)

      - name: Upload AArch64 binary
        uses: actions/upload-artifact@v4
        with:
          name: translatelocally-aarch64
          path: build/translateLocally
